# Site settings
title: Richard Kingston
email: hello@kingstonrichard.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Here are the thoughts of a local gov IT manager, web developer, electronics hobbyist, MTB rider, and father of two.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kingstonrichard.uk" # the base hostname & protocol for your site
twitter_username: kingstonrichard
github_username:  kingstonrichard
permalink: /blog/:title/
redirect_from: /:date | date: "%Y%m%d"

# Build settings
markdown: kramdown
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
